server:
  port: 9090
  servlet:    context-path: /TicketApplicationMysql
    
spring:  jpa:    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true    hibernate:      ddl-auto: update
    show-sql: true
      
  datasource:    url: jdbc:mysql://localhost:3306/ticket_db
    username: root 
    password: Password@123
    driver-class-name: com.mysql.jdbc.Driver
    